### ISSUE TITLE
Name error : Output Layers not defined

### ISSUE THREAD

**Issue by prabhasv77** [Alzaib/Autonomous-Self-Driving-Car-GTA-5#1]
Hey, I am able to run the model in colab and download the steer_augentation file from your dataset. after I load the h5 file into test_model_steer.py I am getting a name error saying output_layers not defined. the output_layers are passed as parameters in Yolo implementation. as outs = net.forward(output_layers) can you help me sort this issue

**Comment by Alzaib** [comment]
Hi,
It's been more than 3 years since I worked on this project. I believe I
made an error when pushing the latest repo to github. I think the yolo
integration is not working as expected for the code I have on github. I'll
update that when I have time. However, if you comment out the yolo
implementation, you should be able to run the model

**Comment by Alzaib** [comment]
2 years*
